### ISSUE TITLE
Shellvar doesn't work on Debian Squeeze

### ISSUE THREAD

**Issue by alaunay** [hercules-team/augeasproviders_shellvar#11]
Upgraded from dom/augeasprov 1.2 to the last 2.1.3/2.1.1 , and one of the last system we have with a squeeze doesn't like puppet anymore, with this in the conf:

``` puppet
shellvar { 'apticron-system':
        ensure => 'present',
        target => '/etc/apticron/apticron.conf',
        variable => 'SYSTEM',
        value => "$::fqdn",
        require => Package['apticron'],
}
```

Running puppet agent on the target machine returns this:

```
err: Could not run Puppet configuration client: Resource type shellvar does not support parameter false
```

No more informations when adding -d and -v; it works fine when the shellvar stuff is commented.

**Comment by raphink** [comment]
Which version of puppet/augeas/ruby-augeas/ruby are you using?

Do you have a ```Shellvar``` default applying to the current scope, or is the example you have sufficient to reproduce?

**Comment by alaunay** [comment]
Nope, it's sufficient.

**Comment by alaunay** [comment]
J'avais pas vu la première question...

server side: debian wheezy, with uptodate puppet:
puppet 3.7.4
augeas 0.10
augeas-ruby 0.4.1
ruby 1.8.7 (or 1.9.3)

it does work troubleless on debian wheezy clients.

Trouble is with a debian squeeze client (vanilla):
puppet 2.6.2
augeas 0.7.2
ruby-augeas 0.3.0
ruby 1.8.7

**Comment by raphink** [comment]
Augeas 0.7.2 is very likely to be the issue. We only test the module against augeas 0.10+ (which is already quite old).

I'd recommend you use a newer version of augeas (camptocamp has augeas 1.3 packages for squeeze at http://pkg.camptocamp.net/).

Squeeze is also not supported by Debian anymore, so there's no reason for us to attempt to support augeas 0.7.2 here.

Can you test on squeeze with a newer augeas version and confirm if it works please?

**Comment by alaunay** [comment]
squeeze-lts is still supported. I've only got a few servers still using it, but I doubt there'll be any upgrade on those any time soon...

I'll try with the augeas from squeeze-backports, I'll ke you posted.

**Comment by alaunay** [comment]
Seems it's somewhere else:

# dpkg -l |grep aug
ii  augeas-lenses                         0.10.0-1~bpo60+3             Set of lenses needed by libaugeas0 to parse config files
ii  augeas-tools                          0.7.2-1+deb6u1               Augeas command line tools
ii  libaugeas-ruby                        0.3.0-1.1                    Augeas bindings for the Ruby language
ii  libaugeas-ruby1.8                     0.3.0-1.1                    Augeas bindings for the Ruby language
ii  libaugeas0                            0.10.0-1~bpo60+3             Augeas configuration editing library and API

debug: report supports formats: b64_zlib_yaml pson raw yaml; using pson
err: Could not run Puppet configuration client: Resource type shellvar does not support parameter false

Not sure if it's in augeas or at the puppet client level.

(I can give you ssh root access if needed)

**Comment by raphink** [comment]
Debian squeeze has been EOL for 3 years, I'll close this.

**Comment by alaunay** [comment]
Agreed ! 👍

**Comment by raphink** [comment]
@alaunay Sorry I did not follow up on this issue.

**Comment by alaunay** [comment]
No problem, it was a first-degree answer, I *do* agree. squeeze is dead, ans so is wheezy. I still have some, but the augeas modifications were hand-made, and I'm just waiting for those old servers to die... :)
