### ISSUE TITLE
Cannot use both comment = "" and uncomment = true

### ISSUE THREAD

**Issue by eLvErDe** [hercules-team/augeasproviders_shellvar#12]
As discussed on with raphik on IRC, I can use one of them but not both at the same:

> 08:51 < raphink> the problem seems to come from comment => ""
> 08:52 < raphink> shellvar { 'TMPTIME': ensure => present, target => "/tmp/rcS", value => "42", }
> 08:52 < raphink> and
>08:52 < raphink> shellvar { 'TMPTIME': ensure => present, target => "/tmp/rcS", value => "42",  uncomment => true }
> 08:52 < raphink> both work
> 08:52 < raphink> but comment => "" doesn't
> 08:52 < acecile> I saw that on the official documentation
> 08:52 < acecile> I guess
> 08:52 < acecile> :D
> 08:52 < raphink> you can open a bug against augeasproviders_ssh for that
> 08:52 -!- dcaro|not_here is now known as dcaro
> 08:52 < raphink> yes, it's used to remove the comment associated with the entry
> 08:53 < raphink> shellvar { 'TMPTIME': ensure => present, target => "/tmp/rcS", value => "42", comment => "" }
> 08:53 < raphink> works as well
> 08:53 < raphink> but not the combination of specifying uncomment (to either false or true) and comment
> 08:54 < raphink> sorry, meant augeasproviders_shellvar for the bug report

**Comment by raphink** [comment]
@eLvErDe what do you expect the result to be when using both attributes together?

**Comment by eLvErDe** [comment]
Hey raphink,

Tbh I don't really remember what this issue was about: Apologize for the crappy bug report, you should probably close this issue.

Adam.

**Comment by raphink** [comment]
Haha, ok! Let's close that old issue...
