### ISSUE TITLE
problem with exclude in yum.conf

### ISSUE THREAD

**Issue by alexdga** [hercules-team/augeasproviders_shellvar#16]
I try to use shellvar to set excludes in /etc/yum.conf

shellvar{'exclude':
ensure=>present,
target=>'/etc/yum.conf',
value=>'mongodb-org*'
}

Puppet run error

Error: /Stage[main]/Mongodb::Install/Shellvar[exclude]: Could not evaluate: Augeas didn't load /etc/yum.conf with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:1, character:0)

**Comment by raphink** [comment]
Yum.conf is not a shellvar file. It is an INI file with sections, which cannot be parsed as a shell file.

You should use the `ini_setting ` type to modify it.

**Comment by alexdga** [comment]
Ok thank you :)
